### ISSUE TITLE
Cannot run with STK1A32SC Intel Compute Stick

### ISSUE THREAD

**Issue by imrehg** [resin-os/resin-intel#101]
Looks like resinOS does not find any storage device (should be probably `mmcblk0`)

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_75z5)

**Comment by floion** [comment]
Fixed by https://github.com/resin-os/resin-intel/pull/106
