### ISSUE TITLE
missing cdc_acm kernel module needed for many cellular modems

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resin-intel#117]
Ran this on Resin OS 2.12.0+rev1 (prod)
```
root@5ac66e4:~# modprobe cdc_acm
modprobe: FATAL: Module cdc_acm not found in directory /lib/modules/4.12.12-yocto-standard
```

**Comment by floion** [comment]
@shaunmulligan should we have this in meta-resin instead?

**Comment by floion** [comment]
Closing this issue as a more generic oen has been opened: https://github.com/resin-os/meta-resin/issues/1033
