### ISSUE TITLE
Firmware missing for Intel Dual Band Wireless-AC 8260

### ISSUE THREAD

**Issue by telphan** [resin-os/resin-intel#18]
The needed firmware is  iwlwifi-8000*

**Comment by petrosagg** [comment]
Is this fixed now?

**Comment by agherzan** [comment]
@petrosagg No. There should be a PR referenced otherwise.

**Comment by petrosagg** [comment]
Is this unrelated? https://github.com/resin-os/meta-resin/pull/230/files

**Comment by agherzan** [comment]
It is. I think this is for a 5GHz dongle. @telphan to confirm.

**Comment by agherzan** [comment]
This issue was moved to resin-os/resinos#69
