### ISSUE TITLE
Missing ip6table_nat ,nf_nat_ipv6 kernel modules in the nuc rootfs

### ISSUE THREAD

**Issue by floion** [resin-os/resin-intel#26]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_l3k)

**Comment by ab77** [comment]
Guys, any update on this?

**Comment by floion** [comment]
Hi, these modules will be available in the next resin.io host OS release.
