### ISSUE TITLE
ipset kernel module/support missing?

### ISSUE THREAD

**Issue by ab77** [resin-os/resin-intel#29]
Looks like something is missing from the kernel to support `ipset`:

```
root@intel-corei7-64-06fd714:/# ipset create domain-filter-ipv4 hash:net                                                                   
ipset v6.23: Kernel error received: Invalid argument                                                                                       
```

```                                                                          
root@intel-corei7-64-06fd714:/# ipset list                                                                                                 
ipset v6.23: Kernel error received: Invalid argument   
```

The same works fine on the RPi1, RPi2 and RPi3 builds.

This one is a show-stopper.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_lsz)

**Comment by floion** [comment]
Thank you for the report. We will take this on and let you know.

**Comment by agherzan** [comment]
This issue was moved to resin-os/resinos#68
